# Package

In [2]:
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

In [3]:
import pandas as pd
import numpy as np
#from sklearn.neighbors import NearestNeighbors
from numpy import array
from numpy.linalg import norm

from operator import itemgetter
import timeit

In [4]:
from sklearn.linear_model import LinearRegression

# Functions

In [5]:
def Average(lst): 
    return sum(lst) / len(lst)

In [6]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

In [7]:
def pq_check_rate(test_movie_id,df,userid):
    """
    Input
    ----
        df: df_pq"""
    
    user_index = b_user_dic.get(str(userid))
    
    movie_index =b_item_dic.get(str(test_movie_id))
    
    rating_predict = df[user_index][movie_index]
    return rating_predict

In [8]:
def item_check_value(test_movie_id,mat):
    """
    Input
    ----
        mat: b_item,matrix
    Return
    -----
        a float"""
    
    #user_index = b_user_dic.get(str(userid))
    
    movie_index =b_item_dic.get(str(test_movie_id))
    
    value_predict = mat[0][movie_index]
    return value_predict

In [9]:
def user_check_value(userid,mat):
    """
    Input
    ----
        mat: b_user,matrix"""
    
    user_index = b_user_dic.get(str(userid))
    
    #movie_index =b_item_dic.get(str(test_movie_id))
    
    value_predict = mat[0][user_index]
    return value_predict

In [10]:
def time_check_value(test_movie_id,df,time_bin):
    """
    Input
    ----
        mat: b_time"""
    #print(test_movie_id,time_bin)
    time_index = b_time_dic.get(str(time_bin))
    #print(time_bin,time_index)
    
    movie_index =b_item_dic.get(str(test_movie_id))
    
    
    rating_predict = df[time_index][movie_index]
    return rating_predict

In [11]:
def pariwise_cosin(q):
    """
    Input
    -----
        q: q.csv
    Return
    -----
        """
    
#     q_matrix = q.copy()
#     q_matrix = q_matrix.values
    
#     q_knn_matrix = q_matrix.T
    
    return 1-pairwise_distances(q.values.T, metric="cosine")

In [12]:
def pair_cos_id (test_movie_id):
    """
    Input
    -----
        test_movie_id:int
        pair_cos_q: nparray, pair_cosin_q (global var)
    Return
    -----
        list with index of nearst movie,id of nearest movie"""
    test_movie_index = b_item_dic.get(str(test_movie_id))
    df_cos = pd.DataFrame(pair_cos_q)
    
    
    high_2_info = df_cos[test_movie_index].nlargest(2)
    knn_near_index = np.where(df_cos[test_movie_index] == high_2_info.values[1])[0][0]
    
    #knn_movie_id = b_item_dic.get(str(test_movie_id))
    knn_movie_id  = list(b_item_dic.keys())[list(b_item_dic.values()).index(knn_near_index)] 
    #[knn_near_index,int(knn_movie_id)]
    return int(knn_movie_id)

In [13]:
def avg_rating_train_look_up(movie_id_int):
    """
    Global variable
    ------
        df_data_train:after groupby mean and reset index
        
    Return
    ------
        rating"""
    #print(df_data_train[df_data_train['movieId'] == movie_id_int])
    
    return rating[rating['movieId'] == movie_id_int]['rating'].values[0]

In [14]:
def main_get_rating_knn(test_movie_id):
    """
    Global var
    ------
        pair_cos_q
        df_data_train
    
    Return
    -----
        Get KNN rating """
    nearest_movie_id = pair_cos_id(test_movie_id)
    #print(nearest_movie_id)
    avg_rating_nearest_movie_id = avg_rating_train_look_up(nearest_movie_id)
    #print(avg_rating_nearest_movie_id)
    
    
    return avg_rating_nearest_movie_id

In [15]:
def b_time_user(user_id):
    rating_user = rating[rating['userId'] == user_id]
    rating_group = rating_user[['userId','movieId','bin_num']].values
    
    user_time_movie_list = []
    for j, pair in enumerate(rating_group):
        user_time_movie_list.append((time_check_value(pair[1],b_time,pair[2])))
    return user_time_movie_list
    #time_check_value(test_movie_id,df,time_bin)
    #b_item_col_qiqi.append(b_item_col_qiqi)

# Data

In [37]:
# ################################ #sgd data
# p = pd.read_csv('../output/p_5.csv',index_col='Unnamed: 0')
# #rmse = pd.read_csv('../data/rmse.csv')
# q = pd.read_csv('../output/q_5.csv',index_col='Unnamed: 0') #movie latent values
# #rating = pd.read_csv('../data/ml-latest-small/ratings.csv')
# rating = pd.read_csv('../output/data_bin.csv',index_col = 'Unnamed: 0')
# data_train = pd.read_csv('../output/data_train_add.csv',index_col='Unnamed: 0')
# data_test = pd.read_csv('../output/data_test.csv',index_col='Unnamed: 0')

# b_item = pd.read_csv('../output/b_item.csv',index_col='Unnamed: 0')
# b_time = pd.read_csv('../output/b_time.csv',index_col='Unnamed: 0')
# b_user = pd.read_csv('../output/b_user.csv',index_col='Unnamed: 0')

In [38]:
############################ #als
p = pd.read_csv('../output/P_ALS.csv',index_col='Unnamed: 0')
#rmse = pd.read_csv('../data/rmse.csv')
q = pd.read_csv('../output/Q_ALS.csv',index_col='Unnamed: 0') #movie latent values
#rating = pd.read_csv('../data/ml-latest-small/ratings.csv')
rating = pd.read_csv('../output/data_bin.csv',index_col = 'Unnamed: 0')
data_train = pd.read_csv('../output/data_train_add.csv',index_col='Unnamed: 0')
data_test = pd.read_csv('../output/data_test.csv',index_col='Unnamed: 0')

b_item = pd.read_csv('../output/b_item_ALS.csv',index_col='Unnamed: 0')
b_time = pd.read_csv('../output/b_time_ALS.csv',index_col='Unnamed: 0')
b_user = pd.read_csv('../output/b_user_ALS.csv',index_col='Unnamed: 0')

In [36]:
b_item.head(2)

,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
1,0.149318,-0.196317,-0.270577,-1.038708,-0.333548,0.321816,-0.224026,-0.389339,-0.462687,0.06681,...,-0.456234,0.190282,-0.424639,-0.459428,0.223926,0.246065,-0.868531,-0.054732,-0.043509,0.434575

In [34]:
b_time.head(2)#movie id,bin

,0,1,2,3,4,5,6,7,8,9,...,9714,9715,9716,9717,9718,9719,9720,9721,9722,9723
0,-3.642852,-3.458309,-3.258477,-2.836368,-2.943978,-3.791145,-3.206189,-3.113072,-3.079577,-3.381462,...,-3.104632,-3.048401,-2.961282,-3.160862,-3.104632,-3.160862,-3.104632,-3.104632,-3.20505,-3.277837
1,0.077626,-0.203374,-0.298689,0.073975,-0.073602,0.049277,-0.163726,-0.000800,0.016192,0.004078,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000

# Processing Data

In [28]:
##calculate predict rating matrix
b_time_dic = dict(zip(list(b_time.columns),range(len(b_time.columns)))) #id, index
b_item_dic = dict(zip(list(b_item.columns),range(len(b_item.columns)))) #id, index
b_user_dic = dict(zip(list(b_user.columns),range(len(b_user.columns)))) #id, index

p_matrix = p.values
q_matrix = q.values
b_item = b_item.values
b_time = b_time.values
b_user = b_user.values

In [29]:
mat_pq = q_matrix.T.dot(p_matrix)
df_pq = pd.DataFrame(mat_pq)

In [30]:
pair_cos_q = pariwise_cosin(q)

In [31]:
data_test_sort = data_test.copy()
data_test_sort = data_test_sort.sort_values(by=['userId'])

userId = list(set(rating['userId'])) #a list of user id, int

movie_id = list(q.columns[:]) #list of all movie id,str

In [32]:
len(movie_id)

9724

In [25]:
movie_id

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138',
 '139',
 '140',
 '141',
 '142',
 '143',
 '144',
 '145',
 '146',
 '147',
 '148',
 '149',
 '150',
 '151',
 '152',
 '153',
 '154',
 '155',
 '156',
 '157',
 '158',
 '159',
 '160',
 '161',
 '162',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '170',
 '171',
 '172',
 '173',
 '174',
 '175',
 '176',
 '177',
 '178',
 '179',
 '180',
 '181',
 '182',
 '183',
 '184',
 '185',
 '186',
 '187',
 '188',
 '189',
 '190',
 '191',
 '192',
 '193',
 '194',
 '195',
 '196',
 '197',
 '198',
 '199',
 '200',
 '201',
 '202',
 '203',
 '204',
 '205',
 '206',
 '207',
 '208',
 '209',
 '210',
 '211',
 '212',
 '213',
 '214',
 '215',
 '216',
 '217',
 '218',
 '219',
 '220',
 '221',
 '222',
 '223',
 '224',
 '225',
 '226',
 '227',
 '228',
 '229',
 '230',
 '231',
 '232',
 '233',
 '234',
 '235',
 '236',
 '237',
 '238',
 '239',
 '240',
 '241',
 '242',
 '243',
 '244',
 '245',
 '246',
 '247',
 '248',
 '249',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '256',
 '257',
 '258',
 '259',
 '260',
 '261',
 '262',
 '263',
 '264',
 '265',
 '266',
 '267',
 '268',
 '269',
 '270',
 '271',
 '272',
 '273',
 '274',
 '275',
 '276',
 '277',
 '278',
 '279',
 '280',
 '281',
 '282',
 '283',
 '284',
 '285',
 '286',
 '287',
 '288',
 '289',
 '290',
 '291',
 '292',
 '293',
 '294',
 '295',
 '296',
 '297',
 '298',
 '299',
 '300',
 '301',
 '302',
 '303',
 '304',
 '305',
 '306',
 '307',
 '308',
 '309',
 '310',
 '311',
 '312',
 '313',
 '314',
 '315',
 '316',
 '317',
 '318',
 '319',
 '320',
 '321',
 '322',
 '323',
 '324',
 '325',
 '326',
 '327',
 '328',
 '329',
 '330',
 '331',
 '332',
 '333',
 '334',
 '335',
 '336',
 '337',
 '338',
 '339',
 '340',
 '341',
 '342',
 '343',
 '344',
 '345',
 '346',
 '347',
 '348',
 '349',
 '350',
 '351',
 '352',
 '353',
 '354',
 '355',
 '356',
 '357',
 '358',
 '359',
 '360',
 '361',
 '362',
 '363',
 '364',
 '365',
 '366',
 '367',
 '368',
 '369',
 '370',
 '371',
 '372',
 '373',
 '374',
 '375',
 '376',
 '377',
 '378',
 '379',
 '380',
 '381',
 '382',
 '383',
 '384',
 '385',
 '386',
 '387',
 '388',
 '389',
 '390',
 '391',
 '392',
 '393',
 '394',
 '395',
 '396',
 '397',
 '398',
 '399',
 '400',
 '401',
 '402',
 '403',
 '404',
 '405',
 '406',
 '407',
 '408',
 '409',
 '410',
 '411',
 '412',
 '413',
 '414',
 '415',
 '416',
 '417',
 '418',
 '419',
 '420',
 '421',
 '422',
 '423',
 '424',
 '425',
 '426',
 '427',
 '428',
 '429',
 '430',
 '431',
 '432',
 '433',
 '434',
 '435',
 '436',
 '437',
 '438',
 '439',
 '440',
 '441',
 '442',
 '443',
 '444',
 '445',
 '446',
 '447',
 '448',
 '449',
 '450',
 '451',
 '452',
 '453',
 '454',
 '455',
 '456',
 '457',
 '458',
 '459',
 '460',
 '461',
 '462',
 '463',
 '464',
 '465',
 '466',
 '467',
 '468',
 '469',
 '470',
 '471',
 '472',
 '473',
 '474',
 '475',
 '476',
 '477',
 '478',
 '479',
 '480',
 '481',
 '482',
 '483',
 '484',
 '485',
 '486',
 '487',
 '488',
 '489',
 '490',
 '491',
 '492',
 '493',
 '494',
 '495',
 '496',
 '497',
 '498',
 '499',
 '500',
 '501',
 '502',
 '503',
 '504',
 '505',
 '506',
 '507',
 '508',
 '509',
 '510',
 '511',
 '512',
 '513',
 '514',
 '515',
 '516',
 '517',
 '518',
 '519',
 '520',
 '521',
 '522',
 '523',
 '524',
 '525',
 '526',
 '527',
 '528',
 '529',
 '530',
 '531',
 '532',
 '533',
 '534',
 '535',
 '536',
 '537',
 '538',
 '539',
 '540',
 '541',
 '542',
 '543',
 '544',
 '545',
 '546',
 '547',
 '548',
 '549',
 '550',
 '551',
 '552',
 '553',
 '554',
 '555',
 '556',
 '557',
 '558',
 '559',
 '560',
 '561',
 '562',
 '563',
 '564',
 '565',
 '566',
 '567',
 '568',
 '569',
 '570',
 '571',
 '572',
 '573',
 '574',
 '575',
 '576',
 '577',
 '578',
 '579',
 '580',
 '581',
 '582',
 '583',
 '584',
 '585',
 '586',
 '587',
 '588',
 '589',
 '590',
 '591',
 '592',
 '593',
 '594',
 '595',
 '596',
 '597',
 '598',
 '599',
 '600',
 '601',
 '602',
 '603',
 '604',
 '605',
 '606',
 '607',
 '608',
 '609',
 '610',
 '611',
 '612',
 '613',
 '614',
 '615',
 '616',
 '617',
 '618',
 '619',
 '620',
 '621',
 '622',
 '623',
 '624',
 '625',
 '626',
 '627',
 '628',
 '629',
 '630',
 '631',
 '632',
 '633',
 '634',
 '635',
 '636',
 '637',
 '638',
 '639',
 '640',
 '641',
 '642',
 '643',
 '644',
 '645',
 '646',
 '647',
 '648',
 '649',
 '650',
 '651',
 '652',
 '653',
 '654',
 '655',
 '656',
 '657',
 '658',
 '659',
 '660',
 '661',
 '662',
 '663',
 '664',
 '665',
 '666',
 '667',
 '668',
 '669',
 '670',
 '671',
 '672',
 '673',
 '674',
 '675',
 '676',
 '677',
 '678',
 '679',
 '680',
 '681',
 '682',
 '683',
 '684',
 '685',
 '686',
 '687',
 '688',
 '689',
 '690',
 '691',
 '692',
 '693',
 '694',
 '695',
 '696',
 '697',
 '698',
 '699',
 '700',
 '701',
 '702',
 '703',
 '704',
 '705',
 '706',
 '707',
 '708',
 '709',
 '710',
 '711',
 '712',
 '713',
 '714',
 '715',
 '716',
 '717',
 '718',
 '719',
 '720',
 '721',
 '722',
 '723',
 '724',
 '725',
 '726',
 '727',
 '728',
 '729',
 '730',
 '731',
 '732',
 '733',
 '734',
 '735',
 '736',
 '737',
 '738',
 '739',
 '740',
 '741',
 '742',
 '743',
 '744',
 '745',
 '746',
 '747',
 '748',
 '749',
 '750',
 '751',
 '752',
 '753',
 '754',
 '755',
 '756',
 '757',
 '758',
 '759',
 '760',
 '761',
 '762',
 '763',
 '764',
 '765',
 '766',
 '767',
 '768',
 '769',
 '770',
 '771',
 '772',
 '773',
 '774',
 '775',
 '776',
 '777',
 '778',
 '779',
 '780',
 '781',
 '782',
 '783',
 '784',
 '785',
 '786',
 '787',
 '788',
 '789',
 '790',
 '791',
 '792',
 '793',
 '794',
 '795',
 '796',
 '797',
 '798',
 '799',
 '800',
 '801',
 '802',
 '803',
 '804',
 '805',
 '806',
 '807',
 '808',
 '809',
 '810',
 '811',
 '812',
 '813',
 '814',
 '815',
 '816',
 '817',
 '818',
 '819',
 '820',
 '821',
 '822',
 '823',
 '824',
 '825',
 '826',
 '827',
 '828',
 '829',
 '830',
 '831',
 '832',
 '833',
 '834',
 '835',
 '836',
 '837',
 '838',
 '839',
 '840',
 '841',
 '842',
 '843',
 '844',
 '845',
 '846',
 '847',
 '848',
 '849',
 '850',
 '851',
 '852',
 '853',
 '854',
 '855',
 '856',
 '857',
 '858',
 '859',
 '860',
 '861',
 '862',
 '863',
 '864',
 '865',
 '866',
 '867',
 '868',
 '869',
 '870',
 '871',
 '872',
 '873',
 '874',
 '875',
 '876',
 '877',
 '878',
 '879',
 '880',
 '881',
 '882',
 '883',
 '884',
 '885',
 '886',
 '887',
 '888',
 '889',
 '890',
 '891',
 '892',
 '893',
 '894',
 '895',
 '896',
 '897',
 '898',
 '899',
 '900',
 '901',
 '902',
 '903',
 '904',
 '905',
 '906',
 '907',
 '908',
 '909',
 '910',
 '911',
 '912',
 '913',
 '914',
 '915',
 '916',
 '917',
 '918',
 '919',
 '920',
 '921',
 '922',
 '923',
 '924',
 '925',
 '926',
 '927',
 '928',
 '929',
 '930',
 '931',
 '932',
 '933',
 '934',
 '935',
 '936',
 '937',
 '938',
 '939',
 '940',
 '941',
 '942',
 '943',
 '944',
 '945',
 '946',
 '947',
 '948',
 '949',
 '950',
 '951',
 '952',
 '953',
 '954',
 '955',
 '956',
 '957',
 '958',
 '959',
 '960',
 '961',
 '962',
 '963',
 '964',
 '965',
 '966',
 '967',
 '968',
 '969',
 '970',
 '971',
 '972',
 '973',
 '974',
 '975',
 '976',
 '977',
 '978',
 '979',
 '980',
 '981',
 '982',
 '983',
 '984',
 '985',
 '986',
 '987',
 '988',
 '989',
 '990',
 '991',
 '992',
 '993',
 '994',
 '995',
 '996',
 '997',
 '998',
 '999',
 ...]

In [24]:
###for loop for the KNN part, only movie id considered

tic=timeit.default_timer()

knn_result = []
for i, item in enumerate(movie_id): #l_train_movie
    print(i,item)
    #print(i,item,type(i),type(item)) ##0,1 int, int, index, id
    #print(main_get_rating_knn(item),item,i)
    knn_result.append(main_get_rating_knn(item))
    

toc=timeit.default_timer()
toc - tic #elapsed time in seconds

0 0
1 1
2 2

IndexError: index 0 is out of bounds for axis 0 with size 0

In [22]:
dict_knn_id_rating = dict(zip(movie_id,knn_result))

In [23]:
#produce knn col
tic=timeit.default_timer()

rating_knn_col =[]
for i, item in enumerate(rating['movieId']):
    #print(i,item,type(i),type(item)) #0,1,int,int, index,id
    #based id find rating
    rating_knn_col.append(dict_knn_id_rating.get(str(item)))
toc=timeit.default_timer()
toc - tic #elapsed time in seconds

0.10107748199999378

In [24]:
rating_sub = rating[['userId','movieId','bin_num']].values

In [31]:
#produce pq col

tic=timeit.default_timer()

search_col_result = []
for i, group in enumerate(rating_sub):
    search_col_result.append(pq_check_rate(group[1],df_pq,group[0]))
    
toc=timeit.default_timer()
toc - tic #elapsed time in seconds

3.737251649000001

In [32]:
#produce b_item col

tic=timeit.default_timer()

b_item_col = []
for i, group in enumerate(rating_sub): #userid, movieid
    b_item_col.append(item_check_value(group[0],b_item))
    
toc=timeit.default_timer()
toc - tic #elapsed time in seconds

0.2993297190000135

In [33]:
#produce b_user col
tic=timeit.default_timer()

b_user_col = []
for i, group in enumerate(rating_sub): #userid, movieid
    b_user_col.append(user_check_value(group[0],b_user))
    
toc=timeit.default_timer()
toc - tic #elapsed time in seconds

0.31385928399998875

In [34]:
#produce b_time col
tic=timeit.default_timer()

b_time_col = []
for i, group in enumerate(rating_sub): #userid, movieid,time
    #print(i,group,'group')
    b_time_col.append(time_check_value(group[1],b_time,group[2]))
    
toc=timeit.default_timer()
toc - tic #elapsed time in seconds

0.4747125269999799

In [35]:
rating_merge = rating.copy()
rating_merge['knn'] = rating_knn_col
rating_merge['pq'] = search_col_result
rating_merge['b_item'] = b_item_col
rating_merge['b_user'] = b_user_col
rating_merge['b_time'] = b_time_col

In [36]:
rating_merge_train = rating_merge[:80670]
rating_merge_train.to_csv('rating_merge_train_ALS.csv')

In [41]:
rating_merge_test = rating_merge[80670:]
rating_merge_test.to_csv('rating_merge_test_ALS.csv')

In [43]:
len(rating) == len(rating_merge_test)+len(rating_merge_train)

True

# check

In [38]:
rating_merge_train.head()

,userId,movieId,rating,timestamp,bin_num,knn,pq,b_item,b_user,b_time
1,1,1,4.0,964982703,5,4.5,-0.029501,0.149318,0.706148,0.370191
2,1,3,4.0,964981247,5,4.0,-0.088080,0.149318,0.706148,0.169982
3,1,6,4.0,964982224,5,4.0,-0.017634,0.149318,0.706148,0.005806
4,1,47,5.0,964983815,5,3.5,0.028836,0.149318,0.706148,-0.045230
5,1,50,5.0,964982931,5,4.0,-0.002264,0.149318,0.706148,0.425822

In [39]:
rating_merge_train.shape

(80670, 10)

In [50]:
rating_merge_test.head()

,userId,movieId,rating,timestamp,bin_num,knn,pq,b_item,b_user,b_time
80671,509,53322,3.0,1435994136,20,2.5,0.165285,0.138598,-0.342162,0.487960
80672,509,53956,3.0,1436101754,20,3.0,-0.008070,0.138598,-0.342162,0.197209
80673,509,53993,2.5,1435995535,20,3.5,-0.007114,0.138598,-0.342162,-0.053725
80674,509,54259,3.5,1436393817,20,0.5,0.279479,0.138598,-0.342162,-0.475267
80675,509,54780,3.0,1435998294,20,3.5,0.117361,0.138598,-0.342162,0.431449

In [54]:
x_label = list(rating_merge_test.columns[5:])
x_label

['knn', 'pq', 'b_item', 'b_user', 'b_time']